import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HiOutlineMail } from "react-icons/hi";
import { BsGithub, BsTwitter } from "react-icons/bs";
import { FaLinkedinIn } from "react-icons/fa";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-0 mx-auto h-screen max-w-screen-xl bg-gray-100 p-2">
        {/* header */}
        <header className="flex flex-col  items-center justify-between  rounded-3xl border-2 border-black text-black ">
          <nav className="w-full rounded-3xl">
            <ul className="flex cursor-pointer text-sm font-bold">
              <li className="grid-row-2 group relative grid w-1/2 rounded-tl-3xl  border-b-2 border-r-2 border-black  p-2 hover:bg-gray-100   ">
                <Link href="/" className="px-4 ">
                  Home
                </Link>
                <p className="justify-self-end px-2">01</p>
                <span className="ease absolute bottom-0 left-0 h-1 w-0 bg-black duration-300 group-hover:w-full group-hover:transition-all"></span>
              </li>
              <li className="grid-row-2 group relative grid w-1/2 rounded-tr-3xl border-b-2 border-black p-2 hover:bg-gray-100  lg:rounded-none  lg:border-r-2 ">
                <Link href="/projects" className="px-2">
                  Projects
                </Link>
                <p className="justify-self-end px-2">02</p>
                <span className="ease absolute bottom-0 left-0 h-1 w-0 bg-black duration-300 group-hover:w-full group-hover:transition-all"></span>
              </li>
              <li className="hidden items-center p-4 lg:flex lg:w-full lg:rounded-tr-3xl lg:border-b-2 lg:border-black">
                <ul className="flex w-3/4 items-center gap-2">
                  <li className="flex h-6 w-6 items-center justify-center rounded-full bg-black  text-white hover:bg-gray-800">
                    <FaLinkedinIn size=".9rem" />
                  </li>
                  <li className="flex h-6 w-6 items-center justify-center rounded-full bg-black  text-white hover:bg-gray-800">
                    <BsGithub size=".9rem" />
                  </li>
                  <li className="flex h-6 w-6 items-center justify-center rounded-full bg-black  text-white hover:bg-gray-800">
                    <BsTwitter size=".9rem" />
                  </li>
                </ul>
                <div className="flex w-1/2 justify-between rounded-full bg-black p-1 px-3 text-xs font-normal text-white">
                  <HiOutlineMail size="1rem" />
                  hernanbp.hb@gmail.com
                </div>
              </li>
            </ul>
          </nav>

          <div className="flex h-16 w-full items-center justify-end px-10 lg:h-24">
            <h1 className="font-display text-2xl font-bold lg:text-4xl">
              Hernan B. Paz - Portfolio
            </h1>
          </div>
        </header>
        <section className="flex flex-col lg:flex-row lg:gap-2">
          <div className="mt-2 flex h-96 w-full flex-col justify-between rounded-3xl bg-black p-6 lg:w-1/2">
            <div>
              <h2 className="mb-2 text-4xl text-white">Something Awesome</h2>
              <p className="max-w-md text-sm font-normal text-gray-400">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quibusdam excepturi, recusandae voluptates illum impedit quo.
                Repellat, laudantium! Voluptate, vel quae.
              </p>
            </div>
            <div>
              <p className="text-sm text-white">Wednesday 14th</p>
            </div>
          </div>
          <div className="relative mt-2 flex h-96  w-full  flex-col justify-center overflow-hidden rounded-3xl bg-black p-6 lg:w-1/2">
            <Image
              src={"/t1.png"}
              alt="Picture of the author"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
