import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
import { HiArrowNarrowRight } from "react-icons/hi";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hernan Barrios Paz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.section className="flex h-5/6  flex-col gap-2 lg:flex-row">
        <motion.div
          initial={{ y: 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{
            type: "spring",
            stiffness: 30,
            damping: 10,
            mass: 0.5,
            delay: 0.3,
          }}
          className=" flex h-full  w-full flex-col justify-between rounded-4xl bg-black p-6 lg:w-1/2 lg:p-10"
        >
          <div>
            <h2 className="tracking-snug mb-2 text-3xl font-bold text-white lg:mb-6 lg:text-4.5xl">
              Hello there.
            </h2>
            <p className="text-sm text-gray-300 lg:text-base ">
              I am Hernan a Fullstack Developer based in Buenos Aires 🇦🇷.
              Welcome to my portfolio website, here you can find some of my
              projects and a little bit about me.
            </p>
            <div className="mt-4 h-3 w-full bg-gray-100 lg:mt-8 "></div>
            <div className="mt-2 h-2 w-full bg-gray-300 lg:mt-2 "></div>
            <div className="mt-4 h-1 w-full bg-gray-500 lg:mt-4"></div>
          </div>
          <div>
            <motion.button
              initial={{ y: 100, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{
                type: "spring",
                stiffness: 30,
                damping: 15,
                delay: 0.1,
              }}
              className="group flex items-center  gap-2 rounded-full border border-white p-2 px-6 text-sm text-white hover:bg-white hover:text-black"
            >
              Get Resume
              <HiArrowNarrowRight className="transition ease-in-out group-hover:translate-x-1 group-hover:text-black" />
            </motion.button>
          </div>
        </motion.div>
        <div className="relative flex h-full w-full flex-col  justify-center  gap-2 overflow-hidden rounded-4xl  lg:w-1/2">
          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{
              type: "spring",
              stiffness: 30,
              damping: 10,
              mass: 0.5,
              delay: 0.5,
            }}
            className="flex h-full flex-col justify-between overflow-hidden rounded-4xl bg-ml p-4 lg:p-10"
          >
            <div>
              <h1 className="tracking-snug text-xl font-black leading-none lg:text-3xl">
                Mercadolibre
              </h1>
              <h2 className="text-lg font-normal lg:text-2xl">Frontend</h2>
            </div>

            <div className="flex gap-2 ">
              <Link href="https://mercadolibre-psi.vercel.app/" target="_blank">
                <motion.button
                  initial={{ y: 100, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{
                    type: "spring",
                    stiffness: 30,
                    damping: 15,
                    delay: 0.1,
                  }}
                  className="flex h-full items-center justify-center rounded-4xl bg-black p-2 px-4 text-sm text-white "
                >
                  Live demo
                </motion.button>
              </Link>
              <motion.button
                initial={{ y: 100, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{
                  type: "spring",
                  stiffness: 30,
                  damping: 10,
                  delay: 0.3,
                }}
                className="flex items-center justify-center rounded-4xl border-2 border-black p-2 px-4 text-sm text-black hover:bg-black  hover:text-white "
              >
                Github Repo
              </motion.button>
            </div>
          </motion.div>

          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{
              type: "spring",
              stiffness: 30,
              damping: 15,
              mass: 0.5,
              delay: 0.7,
            }}
            className="flex h-full flex-col justify-between overflow-hidden rounded-4xl bg-violet-300 p-4 lg:p-10"
          >
            <div>
              <h1 className="tracking-snug text-xl font-black leading-none lg:text-3xl">
                Techdemo
              </h1>
              <h2 className="text-lg font-normal lg:text-2xl">Frontend</h2>

              <p className="mt-2 max-w-sm text-sm">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni
                quidem itaque doloremque recusandae blanditiis ipsa officiis,
                deleniti error corporis praesentium nostrum, quibusdam quis
                porro modi!
              </p>
            </div>

            <div className="flex gap-2 ">
              <motion.button
                initial={{ y: 100, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{
                  type: "spring",
                  stiffness: 30,
                  damping: 15,
                  delay: 0.1,
                }}
                className="flex items-center justify-center rounded-4xl bg-black p-2 px-4 text-sm text-white "
              >
                Live demo
              </motion.button>
              <motion.button
                initial={{ y: 100, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{
                  type: "spring",
                  stiffness: 30,
                  damping: 15,
                  delay: 0.3,
                }}
                className="flex items-center justify-center rounded-4xl border-2 border-black p-2 px-4 text-sm text-black hover:bg-black  hover:text-white "
              >
                Github Repo
              </motion.button>
            </div>
          </motion.div>
        </div>
      </motion.section>
    </>
  );
};

export default Home;
