import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { HiOutlineMail } from "react-icons/hi";
import { BsGithub, BsTwitter } from "react-icons/bs";
import { FaLinkedinIn } from "react-icons/fa";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [active, setActive] = useState(false);

  const route = useRouter().pathname;

  useEffect(() => {
    if (route === "/") {
      setActive(true);
    }
  }, [route]);

  return (
    <>
      <Head>
        <title>Hernan Barrios Paz</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-0 mx-auto h-screen max-w-screen-2xl bg-white p-2">
        {/* header */}
        <header className="flex flex-col  items-center justify-between  rounded-4xl border-2 border-black text-black ">
          <nav className="h-16 w-full rounded-4xl">
            <ul className="flex h-full cursor-pointer  text-xsm font-bold">
              <li className="grid-row-2  group relative grid w-1/2 rounded-tl-4xl  border-b-2 border-r-2 border-black  p-2 hover:bg-gray-100   ">
                <Link href="/" className="px-4 ">
                  Home
                </Link>
                <p className="justify-self-end px-2">01</p>
                {/* cambiar a w-0 */}
                <span
                  className={`absolute bottom-0 left-0 h-2 ${
                    active ? "w-full" : 0
                  }  bg-black duration-300 ease-in-out group-hover:w-full group-hover:transition-all`}
                ></span>
              </li>
              <li className="grid-row-2 group relative grid w-1/2 rounded-tr-4xl border-b-2 border-black p-2 hover:bg-gray-100  lg:rounded-none  lg:border-r-2 ">
                <Link href="/projects" className="px-2">
                  Projects
                </Link>
                <p className="justify-self-end px-2">02</p>
                <span className="absolute bottom-0 left-0 h-2 w-0 bg-black duration-300 ease-in-out group-hover:w-full group-hover:transition-all"></span>
              </li>
              <li className="hidden items-center p-4 lg:flex lg:w-full lg:rounded-tr-4xl lg:border-b-2 lg:border-black">
                <ul className="flex w-3/4 items-center gap-2">
                  <li className="flex h-8 w-8 items-center justify-center rounded-full bg-black p-2  text-white hover:bg-gray-800">
                    <FaLinkedinIn size="1rem" />
                  </li>
                  <li className="flex h-8 w-8 items-center justify-center rounded-full bg-black p-2  text-white hover:bg-gray-800">
                    <BsGithub size="1rem" />
                  </li>
                  <li className="flex h-8 w-8 items-center justify-center rounded-full bg-black p-2  text-white hover:bg-gray-800">
                    <BsTwitter size="1rem" />
                  </li>
                </ul>
                <div className="flex h-8 w-1/3 items-center justify-between  rounded-full bg-black p-1 px-3 text-xs font-normal text-white">
                  <HiOutlineMail size="1.125rem" />
                  hernanbp.hb@gmail.com
                </div>
              </li>
            </ul>
          </nav>
          <div className="flex h-16 w-full items-center justify-end px-6 lg:h-32">
            <h1 className="text-2xl font-bold tracking-tight lg:text-6xl">
              Hernan B. Paz - Portfolio.
            </h1>
          </div>
        </header>
        <section className="flex h-5/6 flex-col-reverse pb-2 lg:flex-row ">
          <div className=" flex h-full  w-full flex-col justify-between rounded-4xl bg-black p-6 lg:w-1/2">
            <div>
              <h2 className="mb-2 text-4xl text-white">Something Awesome</h2>
              <p className="max-w-md text-sm font-normal text-gray-400">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quibusdam excepturi, recusandae voluptates illum impedit quo.
                Repellat, laudantium! Voluptate, vel quae.
              </p>
            </div>
            <div>
              <p className="text-sm text-white">Wednesday 14th</p>
            </div>
          </div>
          <div className="relative  flex h-2/5 w-full  flex-col  justify-center overflow-hidden rounded-4xl bg-black p-6 lg:h-full lg:w-1/2">
            <Image
              src={"/t1.png"}
              alt="Picture of the author"
              fill
              style={{ objectFit: "cover" }}
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
